// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pocketpill-homepage/Current.tsx": () => import("../components/mockups/pocketpill-homepage/Current.tsx"),
  "./components/mockups/pocketpill-homepage/TrustedCare.tsx": () => import("../components/mockups/pocketpill-homepage/TrustedCare.tsx")
};
