/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/app'
import { Route as FindRouteImport } from './routes/find'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LineageRouteImport } from './routes/lineage'
import { Route as MentalHealthRouteImport } from './routes/mental-health'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as SpecialtyRouteImport } from './routes/specialty'
import { Route as TelepharmacyRouteImport } from './routes/telepharmacy'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as LineageStartRouteImport } from './routes/lineage_.start'
import { Route as ApiPublicInitializePaymentRouteImport } from './routes/api/public/initialize-payment'
import { Route as ApiPublicVerifyPaymentRouteImport } from './routes/api/public/verify-payment'
import { Route as ApiPublicWebhooksPaystackRouteImport } from './routes/api/public/webhooks/paystack'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const FindRoute = FindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LineageRoute = LineageRouteImport.update({
  id: '/lineage',
  path: '/lineage',
  getParentRoute: () => rootRouteImport,
} as any)
const MentalHealthRoute = MentalHealthRouteImport.update({
  id: '/mental-health',
  path: '/mental-health',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialtyRoute = SpecialtyRouteImport.update({
  id: '/specialty',
  path: '/specialty',
  getParentRoute: () => rootRouteImport,
} as any)
const TelepharmacyRoute = TelepharmacyRouteImport.update({
  id: '/telepharmacy',
  path: '/telepharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const LineageStartRoute = LineageStartRouteImport.update({
  id: '/lineage_/start',
  path: '/lineage/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInitializePaymentRoute =
  ApiPublicInitializePaymentRouteImport.update({
    id: '/api/public/initialize-payment',
    path: '/api/public/initialize-payment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicVerifyPaymentRoute = ApiPublicVerifyPaymentRouteImport.update({
  id: '/api/public/verify-payment',
  path: '/api/public/verify-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksPaystackRoute =
  ApiPublicWebhooksPaystackRouteImport.update({
    id: '/api/public/webhooks/paystack',
    path: '/api/public/webhooks/paystack',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/find': typeof FindRoute
  '/how-it-works': typeof HowItWorksRoute
  '/lineage': typeof LineageRoute
  '/mental-health': typeof MentalHealthRoute
  '/partners': typeof PartnersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/specialty': typeof SpecialtyRoute
  '/telepharmacy': typeof TelepharmacyRoute
  '/trust': typeof TrustRoute
  '/lineage/start': typeof LineageStartRoute
  '/api/public/initialize-payment': typeof ApiPublicInitializePaymentRoute
  '/api/public/verify-payment': typeof ApiPublicVerifyPaymentRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/find': typeof FindRoute
  '/how-it-works': typeof HowItWorksRoute
  '/lineage': typeof LineageRoute
  '/mental-health': typeof MentalHealthRoute
  '/partners': typeof PartnersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/specialty': typeof SpecialtyRoute
  '/telepharmacy': typeof TelepharmacyRoute
  '/trust': typeof TrustRoute
  '/lineage/start': typeof LineageStartRoute
  '/api/public/initialize-payment': typeof ApiPublicInitializePaymentRoute
  '/api/public/verify-payment': typeof ApiPublicVerifyPaymentRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/find': typeof FindRoute
  '/how-it-works': typeof HowItWorksRoute
  '/lineage': typeof LineageRoute
  '/mental-health': typeof MentalHealthRoute
  '/partners': typeof PartnersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/specialty': typeof SpecialtyRoute
  '/telepharmacy': typeof TelepharmacyRoute
  '/trust': typeof TrustRoute
  '/lineage_/start': typeof LineageStartRoute
  '/api/public/initialize-payment': typeof ApiPublicInitializePaymentRoute
  '/api/public/verify-payment': typeof ApiPublicVerifyPaymentRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/app'
    | '/find'
    | '/how-it-works'
    | '/lineage'
    | '/mental-health'
    | '/partners'
    | '/privacy-policy'
    | '/specialty'
    | '/telepharmacy'
    | '/trust'
    | '/lineage/start'
    | '/api/public/initialize-payment'
    | '/api/public/verify-payment'
    | '/api/public/webhooks/paystack'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/app'
    | '/find'
    | '/how-it-works'
    | '/lineage'
    | '/mental-health'
    | '/partners'
    | '/privacy-policy'
    | '/specialty'
    | '/telepharmacy'
    | '/trust'
    | '/lineage/start'
    | '/api/public/initialize-payment'
    | '/api/public/verify-payment'
    | '/api/public/webhooks/paystack'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/app'
    | '/find'
    | '/how-it-works'
    | '/lineage'
    | '/mental-health'
    | '/partners'
    | '/privacy-policy'
    | '/specialty'
    | '/telepharmacy'
    | '/trust'
    | '/lineage_/start'
    | '/api/public/initialize-payment'
    | '/api/public/verify-payment'
    | '/api/public/webhooks/paystack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRoute
  FindRoute: typeof FindRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LineageRoute: typeof LineageRoute
  MentalHealthRoute: typeof MentalHealthRoute
  PartnersRoute: typeof PartnersRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SpecialtyRoute: typeof SpecialtyRoute
  TelepharmacyRoute: typeof TelepharmacyRoute
  TrustRoute: typeof TrustRoute
  LineageStartRoute: typeof LineageStartRoute
  ApiPublicInitializePaymentRoute: typeof ApiPublicInitializePaymentRoute
  ApiPublicVerifyPaymentRoute: typeof ApiPublicVerifyPaymentRoute
  ApiPublicWebhooksPaystackRoute: typeof ApiPublicWebhooksPaystackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find': {
      id: '/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof FindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lineage': {
      id: '/lineage'
      path: '/lineage'
      fullPath: '/lineage'
      preLoaderRoute: typeof LineageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mental-health': {
      id: '/mental-health'
      path: '/mental-health'
      fullPath: '/mental-health'
      preLoaderRoute: typeof MentalHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialty': {
      id: '/specialty'
      path: '/specialty'
      fullPath: '/specialty'
      preLoaderRoute: typeof SpecialtyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telepharmacy': {
      id: '/telepharmacy'
      path: '/telepharmacy'
      fullPath: '/telepharmacy'
      preLoaderRoute: typeof TelepharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lineage_/start': {
      id: '/lineage_/start'
      path: '/lineage/start'
      fullPath: '/lineage/start'
      preLoaderRoute: typeof LineageStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/initialize-payment': {
      id: '/api/public/initialize-payment'
      path: '/api/public/initialize-payment'
      fullPath: '/api/public/initialize-payment'
      preLoaderRoute: typeof ApiPublicInitializePaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verify-payment': {
      id: '/api/public/verify-payment'
      path: '/api/public/verify-payment'
      fullPath: '/api/public/verify-payment'
      preLoaderRoute: typeof ApiPublicVerifyPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/paystack': {
      id: '/api/public/webhooks/paystack'
      path: '/api/public/webhooks/paystack'
      fullPath: '/api/public/webhooks/paystack'
      preLoaderRoute: typeof ApiPublicWebhooksPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRoute,
  FindRoute: FindRoute,
  HowItWorksRoute: HowItWorksRoute,
  LineageRoute: LineageRoute,
  MentalHealthRoute: MentalHealthRoute,
  PartnersRoute: PartnersRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SpecialtyRoute: SpecialtyRoute,
  TelepharmacyRoute: TelepharmacyRoute,
  TrustRoute: TrustRoute,
  LineageStartRoute: LineageStartRoute,
  ApiPublicInitializePaymentRoute: ApiPublicInitializePaymentRoute,
  ApiPublicVerifyPaymentRoute: ApiPublicVerifyPaymentRoute,
  ApiPublicWebhooksPaystackRoute: ApiPublicWebhooksPaystackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
