/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/app'
import { Route as BookRouteImport } from './routes/book'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as CheckoutSlugRouteImport } from './routes/checkout.$slug'
import { Route as PaymentSuccessRouteImport } from './routes/payment.success'
import { Route as ServicesClinicalPharmacyRouteImport } from './routes/services.clinical-pharmacy'
import { Route as ServicesMentalHealthRouteImport } from './routes/services.mental-health'
import { Route as ServicesOncologyRouteImport } from './routes/services.oncology'
import { Route as ApiPublicInitializePaymentRouteImport } from './routes/api/public/initialize-payment'
import { Route as ApiPublicVerifyPaymentRouteImport } from './routes/api/public/verify-payment'
import { Route as ApiPublicWebhooksPaystackRouteImport } from './routes/api/public/webhooks/paystack'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSlugRoute = CheckoutSlugRouteImport.update({
  id: '/checkout/$slug',
  path: '/checkout/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesClinicalPharmacyRoute =
  ServicesClinicalPharmacyRouteImport.update({
    id: '/clinical-pharmacy',
    path: '/clinical-pharmacy',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesMentalHealthRoute = ServicesMentalHealthRouteImport.update({
  id: '/mental-health',
  path: '/mental-health',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesOncologyRoute = ServicesOncologyRouteImport.update({
  id: '/oncology',
  path: '/oncology',
  getParentRoute: () => ServicesRoute,
} as any)
const ApiPublicInitializePaymentRoute =
  ApiPublicInitializePaymentRouteImport.update({
    id: '/api/public/initialize-payment',
    path: '/api/public/initialize-payment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicVerifyPaymentRoute = ApiPublicVerifyPaymentRouteImport.update({
  id: '/api/public/verify-payment',
  path: '/api/public/verify-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksPaystackRoute =
  ApiPublicWebhooksPaystackRouteImport.update({
    id: '/api/public/webhooks/paystack',
    path: '/api/public/webhooks/paystack',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRouteWithChildren
  '/shop': typeof ShopRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/services/clinical-pharmacy': typeof ServicesClinicalPharmacyRoute
  '/services/mental-health': typeof ServicesMentalHealthRoute
  '/services/oncology': typeof ServicesOncologyRoute
  '/api/public/initialize-payment': typeof ApiPublicInitializePaymentRoute
  '/api/public/verify-payment': typeof ApiPublicVerifyPaymentRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRouteWithChildren
  '/shop': typeof ShopRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/services/clinical-pharmacy': typeof ServicesClinicalPharmacyRoute
  '/services/mental-health': typeof ServicesMentalHealthRoute
  '/services/oncology': typeof ServicesOncologyRoute
  '/api/public/initialize-payment': typeof ApiPublicInitializePaymentRoute
  '/api/public/verify-payment': typeof ApiPublicVerifyPaymentRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRouteWithChildren
  '/shop': typeof ShopRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/services/clinical-pharmacy': typeof ServicesClinicalPharmacyRoute
  '/services/mental-health': typeof ServicesMentalHealthRoute
  '/services/oncology': typeof ServicesOncologyRoute
  '/api/public/initialize-payment': typeof ApiPublicInitializePaymentRoute
  '/api/public/verify-payment': typeof ApiPublicVerifyPaymentRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/book'
    | '/contact'
    | '/how-it-works'
    | '/pricing'
    | '/services'
    | '/shop'
    | '/checkout/$slug'
    | '/payment/success'
    | '/services/clinical-pharmacy'
    | '/services/mental-health'
    | '/services/oncology'
    | '/api/public/initialize-payment'
    | '/api/public/verify-payment'
    | '/api/public/webhooks/paystack'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/book'
    | '/contact'
    | '/how-it-works'
    | '/pricing'
    | '/services'
    | '/shop'
    | '/checkout/$slug'
    | '/payment/success'
    | '/services/clinical-pharmacy'
    | '/services/mental-health'
    | '/services/oncology'
    | '/api/public/initialize-payment'
    | '/api/public/verify-payment'
    | '/api/public/webhooks/paystack'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/book'
    | '/contact'
    | '/how-it-works'
    | '/pricing'
    | '/services'
    | '/shop'
    | '/checkout/$slug'
    | '/payment/success'
    | '/services/clinical-pharmacy'
    | '/services/mental-health'
    | '/services/oncology'
    | '/api/public/initialize-payment'
    | '/api/public/verify-payment'
    | '/api/public/webhooks/paystack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PricingRoute: typeof PricingRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  ShopRoute: typeof ShopRoute
  CheckoutSlugRoute: typeof CheckoutSlugRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  ApiPublicInitializePaymentRoute: typeof ApiPublicInitializePaymentRoute
  ApiPublicVerifyPaymentRoute: typeof ApiPublicVerifyPaymentRoute
  ApiPublicWebhooksPaystackRoute: typeof ApiPublicWebhooksPaystackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$slug': {
      id: '/checkout/$slug'
      path: '/checkout/$slug'
      fullPath: '/checkout/$slug'
      preLoaderRoute: typeof CheckoutSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/clinical-pharmacy': {
      id: '/services/clinical-pharmacy'
      path: '/clinical-pharmacy'
      fullPath: '/services/clinical-pharmacy'
      preLoaderRoute: typeof ServicesClinicalPharmacyRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/mental-health': {
      id: '/services/mental-health'
      path: '/mental-health'
      fullPath: '/services/mental-health'
      preLoaderRoute: typeof ServicesMentalHealthRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/oncology': {
      id: '/services/oncology'
      path: '/oncology'
      fullPath: '/services/oncology'
      preLoaderRoute: typeof ServicesOncologyRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/api/public/initialize-payment': {
      id: '/api/public/initialize-payment'
      path: '/api/public/initialize-payment'
      fullPath: '/api/public/initialize-payment'
      preLoaderRoute: typeof ApiPublicInitializePaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verify-payment': {
      id: '/api/public/verify-payment'
      path: '/api/public/verify-payment'
      fullPath: '/api/public/verify-payment'
      preLoaderRoute: typeof ApiPublicVerifyPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/paystack': {
      id: '/api/public/webhooks/paystack'
      path: '/api/public/webhooks/paystack'
      fullPath: '/api/public/webhooks/paystack'
      preLoaderRoute: typeof ApiPublicWebhooksPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServicesRouteChildren {
  ServicesClinicalPharmacyRoute: typeof ServicesClinicalPharmacyRoute
  ServicesMentalHealthRoute: typeof ServicesMentalHealthRoute
  ServicesOncologyRoute: typeof ServicesOncologyRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesClinicalPharmacyRoute: ServicesClinicalPharmacyRoute,
  ServicesMentalHealthRoute: ServicesMentalHealthRoute,
  ServicesOncologyRoute: ServicesOncologyRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  HowItWorksRoute: HowItWorksRoute,
  PricingRoute: PricingRoute,
  ServicesRoute: ServicesRouteWithChildren,
  ShopRoute: ShopRoute,
  CheckoutSlugRoute: CheckoutSlugRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  ApiPublicInitializePaymentRoute: ApiPublicInitializePaymentRoute,
  ApiPublicVerifyPaymentRoute: ApiPublicVerifyPaymentRoute,
  ApiPublicWebhooksPaystackRoute: ApiPublicWebhooksPaystackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
